version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=railway
      - MYSQL_ROOT_PASSWORD=hAhteYs4JlT7uWEln1AC
    ports:
      - "3307:3306"
